# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with packages for moto_msm8960_jbbl configurations
Name: jolla-configuration-moto_msm8960_jbbl
Requires:
- pattern:jolla-hw-adaptation-moto_msm8960_jbbl

- patterns-sailfish-applications
- patterns-sailfish-ui
# For devices with cellular modem. Those without one, please comment out:
- patterns-sailfish-cellular-apps
# Early stages of porting benefit from these:
- pattern:sailfish-porter-tools

- sailfish-content-graphics-z@ICON_RES@

# For multi-SIM devices
#- jolla-settings-networking-multisim

# Introduced starting Sailfish OS 2.0.4.x:
# 3rd party accounts like Twitter, VK, cloud services, etc
- jolla-settings-accounts-extensions-3rd-party-all

# Introduced starting Sailfish OS 2.1.1.26
# Required for Jolla Store Access
- patterns-sailfish-consumer-generic

# For Mozilla location services (online)
- geoclue-provider-mlsdb

# Sailfish OS CSD tool for hardware testing
# needs some configuration to get all features working
- csd

- jolla-settings-system-flashlight
- jolla-settings-system-nfc

# Pre-installed applications
- sailfish-office
- jolla-calculator
- jolla-email
- jolla-notes
- jolla-clock
- jolla-mediaplayer
- jolla-calendar
- sailfish-weather

Summary: Jolla Configuration moto_msm8960_jbbl

